__version__ = "0.0.1"
from crm_custom.custom.override import create_customer_in_erpnext as custom_create_customer_in_erpnext
import crm.fcrm.doctype.erpnext_crm_settings.erpnext_crm_settings

crm.fcrm.doctype.erpnext_crm_settings.erpnext_crm_settings.create_customer_in_erpnext = custom_create_customer_in_erpnext